---
title: "Geospatial Network"
output: html_notebook
---



```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggmap)
library(readr)
library(plotly)
```

```{r ,data}
set.seed(27)
raw <- read_csv("SAMB_cohort_network.csv",
                col_types = cols(ID = col_skip(), `Other Explained` = col_skip()))

loc <- read_csv("coordinates.csv",
                col_types = cols(X1 = col_skip()))

#Noise was introduced so all the nodes aren't on top of each other
loc$noiselon <- runif(404, min = -0.0900, max = 0.0900)
loc$noiselat <- runif(404, min = -0.0900, max = 0.0900)
loc$lon = loc$lon + loc$noiselon
loc$lat = loc$lat + loc$noiselat

```

# Edges 
```{r, clean}

df <- left_join(raw,loc, by = c("Ego" = "name"))
df <- left_join(df, loc, by = c("Alter" = "name"))


edges <- df 
edges$Strength[edges$Strength == "Communicate"] <- 1
edges$Strength[edges$Strength == "Coordinate"] <- 10
edges$Strength[edges$Strength == "Collaborate"] <-20
edges$Strength[is.na(edges$Strength)] <- 1
edges$Strength <- as.numeric(edges$Strength)

edges$legacy.z <- ""
edges$legacy.z[edges$legacy.x == "SA" & edges$legacy.y == "SA"] <-"SA"
edges$legacy.z[edges$legacy.x == "SA" & edges$legacy.y == "MB"] <-"MB-SA"
edges$legacy.z[edges$legacy.x == "MB" & edges$legacy.y == "SA"] <-"MB-SA"
edges$legacy.z[edges$legacy.x == "MB" & edges$legacy.y == "MB"] <-"MB"


edges$legacy.z <- factor(
  edges$legacy.z,
  levels =
    c("SA", "MB", "MB-SA"),
  exclude = NULL,
  ordered = TRUE
)

```

# Nodes 
```{r, centrality_and_nodes}
SAMB_Staff_Centrality <-
  read_csv(
    "C:/Users/tenis/OneDrive/Desktop/Data_Projects/USFWS/Data/SAMB (USFWS) share folder/SAMB R/SAMB Staff Centrality.csv",
    col_types = cols(
      X1 = col_skip(),
      admin = col_skip(),
      city = col_skip(),
      conservation_delivery = col_skip(),
      conservation_planning = col_skip(),
      email = col_skip(),
      inDegree1 = col_skip(),
      outDegree1 = col_skip(),
      program = col_skip(),
      regulatory_policy = col_skip(),
      relationships = col_skip(),
      research = col_skip(),
      state = col_skip(),
      teamlead = col_skip(),
      technical_species_habitats = col_skip(),
      title = col_skip()
    )
  )

nodes <- left_join(SAMB_Staff_Centrality, loc, by = "name")

nodes <- nodes %>%  mutate(rank_betweenness = dense_rank(desc(betweenness1)), rank_degree = dense_rank(desc(TotalDegree)))

nodes$legacy.x <- factor(
  nodes$legacy.x,
  levels =
    c("SA", "MB"),
  exclude = NULL,
  ordered = TRUE
)


```




```{r, plotly}
# map projection
geo <- list(
  scope = 'north america',
  projection = list(type = 'azimuthal equal area'),
  showland = TRUE,
  landcolor = toRGB("grey83"),
  countrycolor = toRGB("white"),
  subunitcolor = toRGB("white"),
  showlakes = TRUE,
  lakecolor = toRGB("white"),
  showsubunits = TRUE,
  showcountries = TRUE,
  resolution = 50
)


cols <- c("#343477", "#277553", "#AA7939")

#Nodes
fig <- plot_geo(locationmode = 'USA-states')

#Edges
fig <- fig %>% add_segments(
  data = edges,
  x = ~ lon.x,
  xend = ~ lon.y,
  y = ~ lat.x,
  yend = ~ lat.y,
  alpha = 0.6,
  size = ~ Strength,
  hoverinfo = "none",
  color = ~ legacy.z,
  colors = cols
)

fig <- fig %>% add_markers(
  data = nodes,
  x = ~ lon,
  y = ~ lat,
  text = ~ paste0(
    name,
    "<br>",
    "Connections: ",
    TotalDegree,
    "\nConnection Rank: ",
    rank_degree,
    "<br>",
    "City: ",
    address,
    "\nBetweenness: ",
    betweenness1,
    "\nBetweenness Rank: ",
    rank_betweenness
  ),
  size = ~ TotalDegree ** 2,
  hoverinfo = "text",
  alpha = 0.8,
  color = ~ legacy.x,
  colors = cols
)


fig <- fig %>% layout(title = 'SAMB Staff Network',
                      geo = geo,
                      showlegend = TRUE)

library(htmlwidgets)
saveWidget(fig, "SAMB_network.html", selfcontained = T, libdir = "lib")

fig

```


# Network with external partners 


```{r, read}

external <- read_csv(
  "external_network_clean.csv",
  col_types = cols(
    `Budget and Administration` = col_skip(),
    Landscape = col_skip(),
    Other = col_skip(),
    `Other Area` = col_skip(),
    Permitting = col_skip(),
    Science = col_skip(),
    city = col_skip(),
    state = col_skip()
  )
)

```

# External Edges 

# Edges 
```{r, clean_external}

df <- left_join(external, loc, by = c("ego" = "name"))
df <- left_join(df, loc, by = c("alter" = "name"))


edges <- df
edges$Nature_adj[is.na(edges$Nature)] <- 1
edges$Nature_adj[edges$Nature == "Communication"] <- 1
edges$Nature_adj[edges$Nature == "Coordination"] <- 1
edges$Nature_adj[edges$Nature == "Collaboration"] <- 1
edges$Nature_adj <- as.numeric(edges$Nature_adj)
edges <- edges[!is.na(edges$Nature), ]
edges$Nature <- as.factor(edges$Nature)

#This creates an ordered factor.
edges$Nature <- factor(
  edges$Nature,
  levels =
    c("Communication", "Coordination", "Collaboration"),
  exclude = NULL,
  ordered = TRUE
)

edges$Connection <- "Connection"
edges$Connection <- factor(
  edges$Connection,
  levels =
    c("Connection"),
  exclude = NULL,
  ordered = TRUE
)




```

# Nodes 


```{r, nodes}

SAMB_Partners_Centrality <-
  read_csv(
    "C:/Users/tenis/OneDrive/Desktop/Data_Projects/USFWS/Data/SAMB (USFWS) share folder/SAMB R/SAMB_Partners_Centrality.csv",
    col_types = cols(
      X1 = col_skip(),
      admin = col_skip(),
      city = col_skip(),
      conservation_delivery = col_skip(),
      conservation_planning = col_skip(),
      email = col_skip(),
      legacy = col_skip(),
      regulatory_policy = col_skip(),
      relationships = col_skip(),
      research = col_skip(),
      state = col_skip(),
      teamlead = col_skip(),
      technical_species_habitats = col_skip(),
      title = col_skip()
    )
  )

nodes <- left_join(SAMB_Partners_Centrality, loc, by = "name")

nodes$affiliation <- ""

nodes$affiliation[nodes$organization.x == "SAMB"] <- "SAMB"
nodes$affiliation[nodes$organization.x != "SAMB"] <- "Partner"
nodes$affiliation <- as.factor(nodes$affiliation)
nodes$affiliation <- factor(
  nodes$affiliation,
  levels =
    c("Partner", "SAMB"),
  exclude = NULL,
  ordered = TRUE
)

nodes <- nodes[!is.na(nodes$address), ]

nodes$TotalDegree_adj <- nodes$TotalDegree + 10


nodes <-
  nodes %>%  mutate(connection_rank = dense_rank(desc(TotalDegree)))


```

# Partner Network

```{r, plotly}
# map projection
geo <- list(
  scope = 'north america',
  projection = list(type = 'azimuthal equal area'),
  showland = TRUE,
  landcolor = toRGB("grey83"),
  countrycolor = toRGB("white"),
  subunitcolor = toRGB("white"),
  showlakes = TRUE,
  lakecolor = toRGB("white"),
  showsubunits = TRUE,
  showcountries = TRUE,
  resolution = 50
)

cols <- c("#AA7939", "#343477", "#277553")

#Nodes
fig <- plot_geo(locationmode = 'USA-states')


#Edges
fig <- fig %>% add_segments(
  data = edges,
  x = ~ lon.x,
  xend = ~ lon.y,
  y = ~ lat.x,
  yend = ~ lat.y,
  alpha = 0.6,
  hoverinfo = "none",
  color = ~ Connection,
  colors = cols
)

fig <- fig %>% layout(title = 'SAMB Partner Network',
                      geo = geo,
                      showlegend = TRUE)


fig <- fig %>% add_markers(
  data = nodes,
  x = ~ lon,
  y = ~ lat,
  text = ~ paste0(
    name,
    "<br>",
    "Connections: ",
    TotalDegree,
    "\nConnection Rank: ",
    connection_rank,
    "<br>",
    "City: ",
    address
  ),
  size = ~ TotalDegree_adj ** 2,
  hoverinfo = "text",
  alpha = 0.8,
  color = ~ affiliation,
  colors = cols
)



library(htmlwidgets)
saveWidget(fig,
           "SAMB_External_Network.html",
           selfcontained = T,
           libdir = "lib2")

fig

```

# USFWS Network 

```{r ,data}
set.seed(27)

raw <-
  read_csv(
    "C:/Users/tenis/OneDrive/Desktop/Data_Projects/USFWS/Data/SAMB (USFWS) share folder/SAMB R/USFWS_network_in region.csv",
    col_types = cols(
      `Budget and Administration` = col_skip(),
      Landscape = col_skip(),
      Other = col_skip(),
      `Other Area` = col_skip(),
      Permitting = col_skip(),
      Science = col_skip(),
      X1 = col_skip()
    )
  )

loc <-
  read_csv(
    "C:/Users/tenis/OneDrive/Desktop/Data_Projects/USFWS/Data/SAMB (USFWS) share folder/SAMB R/coordinates_USFWS.csv",
    col_types = cols(X1 = col_skip())
  )

#Noise was introduced so all the nodes aren't on top of each other
loc$noiselon <- runif(288, min = -0.0900, max = 0.0900)
loc$noiselat <- runif(288, min = -0.0900, max = 0.0900)
loc$lon = loc$lon + loc$noiselon
loc$lat = loc$lat + loc$noiselat
```

```{r edges_USFWS}
df <- left_join(raw,loc, by = c("Ego" = "name"))
df <- left_join(df, loc, by = c("Alter" = "name"))

edges <- df
edges <- edges[!is.na(edges$Nature), ]
edges$Nature <- as.factor(edges$Nature)

#This creates an ordered factor.
edges$Nature <- factor(
  edges$Nature,
  levels =
    c("Communication", "Coordination", "Collaboration"),
  exclude = NULL,
  ordered = TRUE
)

edges$Connection <- "Connection"
edges$Connection <- factor(
  edges$Connection,
  levels =
    c("Connection"),
  exclude = NULL,
  ordered = TRUE
)

```


```{r, nodes_USFWS}


SAMB_USFWS_Centrality <-
  read_csv(
    "C:/Users/tenis/OneDrive/Desktop/Data_Projects/USFWS/Data/SAMB (USFWS) share folder/SAMB R/SAMB_USFWS_Centrality.csv",
    col_types = cols(X1 = col_skip(), title = col_skip())
  )

nodes <- left_join(SAMB_USFWS_Centrality, loc, by = "name")




nodes$program.x <- as.factor(nodes$program.x)
nodes$program.x <- factor(
  nodes$program.x,
  levels =
    c(
      "Ecological Services",
      "External Affairs",
      "Fisheries and Aquatic Conservation",
      "Gulf Restoration",
      "Information Resources and Technology Management (IRTM)",
      "Joint Administrative Operations",
      "Law Enforcement",
      "Migratory Birds",
      "National Wildlife Refuge System",
      "Regional Director's Office",
      "SAMB",
      "Wildlife and Sport Fish Restoration"
    ),
  exclude = NULL,
  ordered = TRUE
)

nodes <- nodes[!is.na(nodes$address),]

nodes$TotalDegree_adj <- nodes$TotalDegree + 10


nodes <-
  nodes %>%  mutate(connection_rank = dense_rank(desc(TotalDegree)))


```

```{r, plotly_USFWS}
library(plotly)

# map projection
geo <- list(
  scope = 'north america',
  projection = list(type = 'azimuthal equal area'),
  showland = TRUE,
  landcolor = toRGB("grey83"),
  countrycolor = toRGB("white"),
  subunitcolor = toRGB("white"),
  showlakes = TRUE,
  lakecolor = toRGB("white"),
  showsubunits = TRUE,
  showcountries = TRUE,
  resolution = 50
)

cols <-
  c(
    "#800000",
    "#FF0000",
    "#808000",
    "#FFFF00",
    "#008000",
    "#00FF00",
    "#008080",
    "#00FFFF",
    "#000080",
    "#0000FF",
    "#800080",
    "#FF00FF"
  )

#Nodes
fig <- plot_geo(locationmode = 'USA-states')


#Edges
fig <- fig %>% add_segments(
  data = edges,
  x = ~ lon.x,
  xend = ~ lon.y,
  y = ~ lat.x,
  yend = ~ lat.y,
  alpha = 0.6,
  hoverinfo = "none",
  color = ~ Connection,
  colors = cols
)

fig <- fig %>% layout(title = 'SAMB Partner Network',
                      geo = geo,
                      showlegend = TRUE)


fig <- fig %>% add_markers(
  data = nodes,
  x = ~ lon,
  y = ~ lat,
  text = ~ paste0(
    name,
    "<br>",
    "Connections: ",
    TotalDegree,
    "\nConnection Rank: ",
    connection_rank,
    "<br>",
    "City: ",
    address
  ),
  size = ~ TotalDegree_adj ** 2,
  hoverinfo = "text",
  alpha = 0.8,
  color = ~ program.x,
  colors = cols
)



# library(htmlwidgets)
# saveWidget(fig,
#            "SAMB_External_Network.html",
#            selfcontained = T,
#            libdir = "lib2")

fig

```
