---
title: "SAMB-SE FWS Network"
author: "Patrick Bixler"
date: "9/22/2020"
output: html_document
---

```{r include=FALSE}
source("utils2.R")
```

```{r Clean Network Data, include=FALSE}

#edgelist 
el2<-el2
e2<-as.matrix(el2)
e2[,1]=as.character(e2[,1])
e2[,2]=as.character(e2[,2])
e2[,3]=as.character(e2[,3])
e2[,4]=as.character(e2[,4])
e2[,5]=as.character(e2[,5])
e2[,6]=as.character(e2[,6])
e2[,7]=as.character(e2[,7])
e2[,8]=as.character(e2[,8])
e2[,9]=as.character(e2[,9])
e2[,10]=as.character(e2[,10])


g2<-graph_from_data_frame(d=el2,directed=TRUE) 
#Some stats like communities and clusters need undirected graphs. Mode = collapse creates an undirected link between any pair of connected nodes. Here we have also said that the ‘weight’ of the links should be summed, and all other edge attributes ignored and dropped.  
#g2<-as.undirected(g1, mode= "collapse",edge.attr.comb=list(weight="sum", "ignore"))


#Create a nodelist for excel use 
gvis2<-toVisNetworkData(g2)
nodelist2<-gvis2$nodes
nodelist2<-nodelist2[,1]
nodelist2<-as.data.frame(nodelist2)
names(nodelist2)<-c("name")

#load nonsamb_program
#nonsamb_programs<-read.csv("nonsamb_program.csv")

attr_nodelist2<-merge(nodelist2,samb_usfws_3,by = "name",all.x = TRUE)

write.csv(attr_nodelist2,file = "Nodelist2.csv")

# Pull the node list with attributes
input_attributes2<-attr_nodelist2

#Define Attributes
for (i in 1:vcount(g2))
{
V(g2)[i]$program<-input_attributes2$program[which(input_attributes2$name==V(g2)[i]$name)]
V(g2)[i]$type<-input_attributes2$program[which(input_attributes2$name==V(g2)[i]$name)]
}

#new dataframe of landscape connections
el2_landscape<-el2[which(el2$Landscape=="1"),]
e2_landscape<-as.matrix(el2_landscape)

#Landscape are directed
#removed a [,-1] from SDF code after d=e1_landscape
g2_landscape<-graph_from_data_frame(d=e2_landscape,directed=TRUE) 
plot(g2_landscape)

# Define networks based on edge type
el2_BA<-el2[which(el2$Budget.and.Administration=="1"),]
e2_BA<-as.matrix(el2_BA)

#Budget and Administration are directed 
#removed a [,-1] from SDF code at d=el_BA
g2_BA<-graph_from_data_frame(d=e2_BA,directed=TRUE) 


#Make new edgelist of science application connections
el2_science<-el2[which(el2$Science=="1"),]
e2_science<-as.matrix(el2_science)
#Science is directed
g2_science<-graph_from_data_frame(d=e2_science,directed=TRUE) 

plot(g2_science)

#Make new edgelist of permitting connections
el2_permit<-el2[which(el2$Permitting=="1"),]
e2_permit<-as.matrix(el2_permit)
#Permitting is directed
g2_permit<-graph_from_data_frame(d=e2_permit,directed=TRUE) 
plot(g2_permit)
```

$~$

## Ego-centric Network Measures
```{r echo=FALSE}
#Degree in 

inDegree2<-igraph::degree(g2,mode="in")
outDegree2<-igraph::degree(g2,mode="out")
TotalDegree2<-as.data.frame(igraph::degree(g2))
betweenness2<-igraph::betweenness(g2, v = V(g2), directed = TRUE, weights = NULL,
  nobigint = TRUE, normalized = TRUE)
inCloseness2<-igraph::closeness(g2, vids = V(g2), mode = c("in"),normalized = TRUE)
outCloseness2<-igraph::closeness(g2, vids = V(g2), mode = c("out"),normalized = TRUE)
#eigen<-evcent(m1,g=1,gmode = "digraph",rescale=TRUE, ignore.eval=TRUE)
#removed eigen from this DF_Centrality
DF_Centrality2<-as.data.frame(cbind(rownames(TotalDegree2),inDegree2,outDegree2,TotalDegree2,betweenness2,inCloseness2,outCloseness2))
rownames(DF_Centrality2)<-NULL
DF_Centrality2<-as.data.frame(DF_Centrality2)
colnames(DF_Centrality2)[1]<-"name"
colnames(DF_Centrality2)[4]<-"TotalDegree"


par(mfcol = c(4,3)) 
hist(inDegree2)
hist(outDegree2)
hist(TotalDegree2)
hist(betweenness2)
hist(inCloseness2)
hist(outCloseness2)

dd.g2<-degree.distribution(g2)
d2<-1:max(TotalDegree2)-1
ind<-(dd.g2 != 0)
plot(d2[ind],dd.g2[ind],log="xy",col="blue",xlab=c("Log-degree"),ylab=c("Log-Intensity"),
     main="Log-Log Degree Distribution")

samb_usfws_centrality<-merge(DF_Centrality2, attr_nodelist2, by = "name")
write.csv(samb_usfws_centrality,file = "SAMB_USFWS_Centrality.csv")

```

## Network Graphs{.tabset}

<br>


#All relationships
```{r echo=FALSE}

lnodes <- data.frame(label = c("ES","EA", "F&A","Gulf","IRTM","Jnt Ops","Law", "NWRS", "DK", "Diretr", "W&S Fish", "SAMB"),
color.background = c("white","white","white","white","white","white","white","white","white","white", "white", "white"),
color.border = c("green", "darkred","orange", "red", "yellow","gold","gray","purple","darkgreen","darkorange", "darkblue", "black"),
shape=c("circle","circle","circle","circle","circle","circle","circle","circle","circle","circle", "circle", "circle"))

V(g2)[V(g2)$program=="Ecological Services"]$color <- "green"
V(g2)[V(g2)$program=="External Affairs"]$color <- "darkred"
V(g2)[V(g2)$program=="Fisheries and Aquatic Conservation"]$color <- "orange"
V(g2)[V(g2)$program=="Gulf Restoration"]$color <- "red"
V(g2)[V(g2)$program=="Information Resources and Technology Management (IRTM)"]$color <- "yellow"
V(g2)[V(g2)$program=="Joint Administrative Operations"]$color <- "gold"
V(g2)[V(g2)$program=="Law Enforcement"]$color <- "gray"
V(g2)[V(g2)$program=="National Wildlife Refuge System"]$color <- "purple"
V(g2)[V(g2)$program=="Other/Don't Know"]$color <- "darkgreen"
V(g2)[V(g2)$program=="Regional Director's Office"]$color <- "darkorange"
V(g2)[V(g2)$program=="Wildlife and Sport Fish Restoration"]$color <- "darkblue"
V(g2)[V(g2)$program=="SAMB"]$color <- "black"

gvis2<-toVisNetworkData(g2)
nodelist2<-gvis2$nodes
visNetwork(sort(gvis2$nodes),gvis2$edges,main="All Connections",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  #visClusteringByColor(colors = c(green", "darkred","orange", "red", "yellow","gold","gray","purple","darkgreen","darkorange", "darkblue")) %>%
  addFontAwesome() %>%
  visLegend(position = "left",addNodes = lnodes,useGroups = FALSE,stepY=100)
```
#Programs Group Together
```{r echo=FALSE}
gvis2<-toVisNetworkData(g2)
nodelist2<-gvis2$nodes
visNetwork(sort(gvis2$nodes),gvis2$edges,main="All Connections",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  visClusteringByColor(colors = c("green", "darkred","orange", "red", "yellow","gold","gray","purple","darkgreen","darkorange", "darkblue", "black")) %>%
addFontAwesome() %>%
  visLegend(position = "left",addNodes = lnodes,useGroups = FALSE,stepY=100)
```
#Landscape Conservation
```{r echo=FALSE}
#Define Attributes
for (i in 1:vcount(g2_landscape))
{
V(g2_landscape)[i]$program<-input_attributes2$program[which(input_attributes2$name==V(g2_landscape)[i]$name)]
V(g2_landscape)[i]$legacy<-input_attributes2$legacy[which(input_attributes2$name==V(g2_landscape)[i]$name)]
}

lnodes <- data.frame(label = c("SA","MB"),
color.background = c("white", "white"),
color.border = c("red", "green"),
shape=c("circle", "circle"))

V(g2_landscape)[V(g2_landscape)$legacy=="MB"]$color <- "green"
V(g2_landscape)[V(g2_landscape)$legacy=="SA"]$color <- "red"

gvis2_landscape<-toVisNetworkData(g2_landscape)
nodelist2_landscape<-gvis2_landscape$nodes
visNetwork(sort(gvis2_landscape$nodes),gvis2_landscape$edges,main="Landscape Conservation Connections",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left",addNodes = lnodes, useGroups = FALSE,stepY=100)
```
#Science Applications
```{r echo=FALSE}
#Define Attributes
for (i in 1:vcount(g2_science))
{
V(g2_science)[i]$program<-input_attributes2$program[which(input_attributes2$name==V(g2_science)[i]$name)]
}

lnodes <- data.frame(label = c("SAMB"),
color.background = c("white"),
color.border = c("black"),
shape=c("circle"))

V(g2_science)[V(g2_science)$program=="SAMB"]$color <- "black"


gvis2_science<-toVisNetworkData(g2_science)
nodelist2_science<-gvis2_science$nodes
visNetwork(sort(gvis2_science$nodes),gvis2_science$edges,main="Science Support Connections",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left",addNodes = lnodes,useGroups = FALSE,stepY=100)
```
#Permitting
```{r echo=FALSE}
#Define Attributes
for (i in 1:vcount(g2_permit))
{
V(g2_permit)[i]$program<-input_attributes2$program[which(input_attributes2$name==V(g2_permit)[i]$name)]
}

lnodes <- data.frame(label = c("SAMB"),
color.background = c("white"),
color.border = c("black"),
shape=c("circle"))

V(g2_permit)[V(g2_permit)$program=="SAMB"]$color <- "black"




gvis2_permit<-toVisNetworkData(g2_permit)
nodelist2_permit<-gvis2_permit$nodes
visNetwork(sort(gvis2_permit$nodes),gvis2_permit$edges,main="Permittting Connections",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left",addNodes = lnodes,useGroups = FALSE,stepY=100)
```
#Budgeting and Administration
```{r echo=FALSE}
#Define Attributes
for (i in 1:vcount(g2_BA))
{
V(g2_BA)[i]$program<-input_attributes2$program[which(input_attributes2$name==V(g2_BA)[i]$name)]
}

lnodes <- data.frame(label = c("SAMB"),
color.background = c("white"),
color.border = c("black"),
shape=c("circle"))

V(g2_BA)[V(g2_BA)$program=="SAMB"]$color <- "black"


gvis2_BA<-toVisNetworkData(g2_BA)
nodelist2_BA<-gvis2_BA$nodes
visNetwork(sort(gvis2_BA$nodes),gvis2_BA$edges,main="Budgeting and Administration Connections",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left",addNodes = lnodes,useGroups = FALSE,stepY=100)
```