---
title: "SAMB + External Partners"
author: "Patrick Bixler"
date: "9/23/2020"
output: html_document
---

```{r include=FALSE}
source("utils3.R")
```

```{r Clean Network Data, include=FALSE}

#edgelist 
el3<-el3
e3<-as.matrix(el3)
e3[,1]=as.character(e3[,1])
e3[,2]=as.character(e3[,2])
e3[,3]=as.character(e3[,3])
e3[,4]=as.character(e3[,4])
e3[,5]=as.character(e3[,5])
e3[,6]=as.character(e3[,6])
e3[,7]=as.character(e3[,7])
e3[,8]=as.character(e3[,8])
e3[,9]=as.character(e3[,9])
e3[,10]=as.character(e3[,10])
e3[,11]=as.character(e3[,11])
e3[,11]=as.character(e3[,11])

g3<-graph_from_data_frame(d=el3,directed=TRUE) 
#Some stats like communities and clusters need undirected graphs. Mode = collapse creates an undirected link between any pair of connected nodes. Here we have also said that the ‘weight’ of the links should be summed, and all other edge attributes ignored and dropped.  
#g3_un<-as.undirected(g1, mode= "collapse",edge.attr.comb=list(weight="sum", "ignore"))


#Create a nodelist for excel use 
gvis3<-toVisNetworkData(g3)
nodelist3<-gvis3$nodes
nodelist3<-nodelist3[,1]
nodelist3<-as.data.frame(nodelist3)
names(nodelist3)<-c("name")

#load nonsamb_program
#nonsamb_programs<-read.csv("nonsamb_program.csv")

attr_nodelist3<-merge(nodelist3,samb_partners,by = "name",all.x = TRUE)

write.csv(attr_nodelist3,file = "Nodelist3.csv")

# Pull the node list with attributes
input_attributes3<-attr_nodelist3

#Define Attributes
for (i in 1:vcount(g3))
{
V(g3)[i]$organization<-input_attributes3$organization[which(input_attributes3$name==V(g3)[i]$name)]
V(g3)[i]$state<-input_attributes3$state[which(input_attributes3$name==V(g3)[i]$name)]
}

#new dataframe of landscape connections
el3_landscape<-el3[which(el3$Landscape=="1"),]
e3_landscape<-as.matrix(el3_landscape)

#Landscape are directed
#removed a [,-1] from SDF code after d=e1_landscape
g3_landscape<-graph_from_data_frame(d=e3_landscape,directed=TRUE) 
plot(g3_landscape)

# Define networks based on edge type
el3_BA<-el3[which(el3$Budget.and.Administration=="1"),]
e3_BA<-as.matrix(el3_BA)

#Budget and Administration are directed 
#removed a [,-1] from SDF code at d=el_BA
g3_BA<-graph_from_data_frame(d=e3_BA,directed=TRUE) 


#Make new edgelist of science support connections
el3_science<-el3[which(el3$Science=="1"),]
e3_science<-as.matrix(el3_science)
#Science is directed
g3_science<-graph_from_data_frame(d=e3_science,directed=TRUE) 

plot(g3_science)

#Make new edgelist of permitting connections
el3_permit<-el3[which(el3$Permitting=="1"),]
e3_permit<-as.matrix(el3_permit)
#Permitting is directed
g3_permit<-graph_from_data_frame(d=e3_permit,directed=TRUE) 
plot(g3_permit)
```

$~$

## Ego-centric Network Measures
```{r echo=FALSE}
#Degree in 

inDegree3<-igraph::degree(g3,mode="in")
outDegree3<-igraph::degree(g3,mode="out")
TotalDegree3<-as.data.frame(igraph::degree(g3))
betweenness3<-igraph::betweenness(g3, v = V(g3), directed = TRUE, weights = NULL,
  nobigint = TRUE, normalized = TRUE)
inCloseness3<-igraph::closeness(g3, vids = V(g3), mode = c("in"),normalized = TRUE)
outCloseness3<-igraph::closeness(g3, vids = V(g3), mode = c("out"),normalized = TRUE)
#eigen<-evcent(m1,g=1,gmode = "digraph",rescale=TRUE, ignore.eval=TRUE)
#removed eigen from this DF_Centrality
DF_Centrality3<-as.data.frame(cbind(rownames(TotalDegree3),inDegree3,outDegree3,TotalDegree3,betweenness3,inCloseness3,outCloseness3))
rownames(DF_Centrality3)<-NULL
DF_Centrality3<-as.data.frame(DF_Centrality3)
colnames(DF_Centrality3)[1]<-"name"
colnames(DF_Centrality3)[4]<-"TotalDegree"


par(mfcol = c(4,3)) 
hist(inDegree3)
hist(outDegree3)
hist(TotalDegree3)
hist(betweenness3)
hist(inCloseness3)
hist(outCloseness3)

dd.g3<-degree.distribution(g3)
d3<-1:max(TotalDegree3)-1
ind<-(dd.g3 != 0)
plot(d3[ind],dd.g3[ind],log="xy",col="blue",xlab=c("Log-degree"),ylab=c("Log-Intensity"),
     main="Log-Log Degree Distribution")

samb_partners_centrality<-merge(DF_Centrality3, attr_nodelist3, by = "name")
write.csv(samb_partners_centrality,file = "SAMB_Partners_Centrality.csv")

```
#Visualize All Partner Network 
```{r echo=FALSE}
gvis3<-toVisNetworkData(g3)
nodelist3<-gvis3$nodes
visNetwork(sort(gvis3$nodes),gvis3$edges,main="SAMB Connections to External Partners",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("state"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  #visClusteringByColor(colors = c(green", "darkred","orange", "red", "yellow","gold","gray","purple","darkgreen","darkorange", "darkblue")) %>%
  addFontAwesome() %>%
  visLegend(position = "left",useGroups = FALSE,stepY=100)
```
#Visualize Landscape Conservation Network 
```{r echo=FALSE}
gvis3_landscape<-toVisNetworkData(g3_landscape)
nodelist3_landscape<-gvis3_landscape$nodes
visNetwork(sort(gvis3_landscape$nodes),gvis3_landscape$edges,main="Landscape Conservation Connections with External Partners",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left", useGroups = FALSE,stepY=100)
```
#Science Support
```{r echo=FALSE}
#Define Attributes
for (i in 1:vcount(g3_science))
{
V(g3_science)[i]$organization<-input_attributes3$organization[which(input_attributes3$name==V(g3_science)[i]$name)]
}

lnodes <- data.frame(label = c("SAMB"),
color.background = c("white"),
color.border = c("black"),
shape=c("circle"))

#V(g3_science)[V(g3_science)$organization=="SAMB"]$color <- "black"


gvis3_science<-toVisNetworkData(g3_science)
nodelist3_science<-gvis3_science$nodes
visNetwork(sort(gvis3_science$nodes),gvis3_science$edges,main="Science Support Connections with External Partners",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 15) %>%
  visEdges(arrows = 'to', smooth =T)  %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE) %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left",useGroups = FALSE,stepY=100)
```

